/* Database schema to keep the structure of entire database. */

DROP TABLE IF EXISTS animals;
CREATE TABLE animals(
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
	name TEXT NOT NULL,
	date_of_birth date,
	escape_attempts INT,
	neutered BOOL,
	weight_kg DEC
);
