/* Database schema to keep the structure of entire database. */
-- DAY 1
DROP TABLE IF EXISTS animals;
CREATE TABLE animals(
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
	name TEXT NOT NULL,
	date_of_birth date,
	escape_attempts INT,
	neutered BOOL,
	weight_kg DEC
);

-- DAY 2
ALTER TABLE animals ADD species TEXT;

-- DAY 3
DROP TABLE IF EXISTS owners;
CREATE TABLE owners(
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
	full_name TEXT NOT NULL,
	age INT
);

DROP TABLE IF EXISTS species;
CREATE TABLE species(
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
	name TEXT NOT NULL
);

ALTER TABLE animals
	DROP COLUMN species;

ALTER TABLE animals
	ADD species_id INT;

ALTER TABLE animals
	ADD species_id INT,
	ADD FOREIGN KEY (species_id) REFERENCES species(id);

ALTER TABLE animals
	ADD owner_id INT,
	ADD FOREIGN KEY (owner_id) REFERENCES owners(id);


